movie_app/urls.py
from django.urls import path, include
from .views import *

app_name = 'movie'

urlpatterns = [
    path('', MovieList.as_view(), name = 'movie_list'),
    path('search/', MovieSearch.as_view(), name = 'movie_search'),
    path('genre/<str:genre>', MovieGenre.as_view(), name ='movie_genre'),
    path("<slug:slug>/", movie_detail, name="movie_detail"),
    path('recommend/<str:username>/<str:title>', RecommendListView.as_view(), name = 'movie_recommend'),
    path('my_recommendations/<str:username>',MyRecommendView.as_view(),name='my_recommendations'),
    path('my_liked/<str:username>',MyLikedView.as_view(),name='my_liked'),
]

movie_recommender/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from movie_app.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', HomeView.as_view(), name = 'home'),
    path('movie/', include('movie_app.urls', namespace='movie')),
    path('register/', register, name = 'register'),
    path('accounts/', include('allauth.urls')),
    path('contact/', contact, name = 'contact'),
    path('add_admin/', AddMovie_admin, name='add_admin'),
    path('add_movie_submission/', add_movie_submission, name='add_movie_submission'),
    path('about_us/', about_us, name = 'about_us'),
    path('', auth_views.LoginView.as_view(template_name = 'movie_app/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'movie_app/logout.html'), name = 'logout'),
]
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie_app/models.py
from django.db import models
from django.utils.text import slugify
from django.utils import timezone
from django_mysql.models import ListCharField
from django.db.models import CharField
from datetime import date
# Create your models here.

GENRE_CHOICES = (
    ('adventure', 'ADVENTURE'),
    ('fantasy', 'FANTASY'),
    ('science_fiction', 'SCIENCE FICTION'),
    ('action', 'ACTION'),
    ('comedy', 'COMEDY'),
    ('romance', 'ROMANCE'),
)

class Movie(models.Model):
    title = models.CharField(max_length = 100, unique=True)
    description = models.TextField(max_length = 1000)
    image = models.ImageField(upload_to = 'movie')
    cast = models.CharField(max_length = 500)
    genre1 = models.CharField(choices = GENRE_CHOICES, max_length = 40)
    genre2 = models.CharField(choices = GENRE_CHOICES, max_length = 40,blank=True)
    genre3 = models.CharField(choices = GENRE_CHOICES, max_length = 40,blank=True)
    imdbrating = models.FloatField(default=0)
    box_office = models.FloatField(default=0)
    year_of_release = models.DateField(default=date.today)

    slug = models.SlugField(blank = True, null = True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Movie, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class MyRecommender(models.Model):
        movie_name = ListCharField(base_field=CharField(max_length=100),max_length=(6*100))
        user_name =  models.CharField(max_length = 100)
        liked_movie = models.CharField(max_length = 100)


class Comment(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return "Comment {} by {}".format(self.body, self.name)

movie_app/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class DateInput(forms.DateInput):
    input_type = 'date'

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required = False)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class MovieForm(forms.ModelForm):

    class Meta:
        model = Movie
        exclude = ['slug']
        widgets = {
            'year_of_release': DateInput()
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

movie_app/views.py
import recommend
from django.shortcuts import render, redirect,get_object_or_404
from django.views.generic import ListView, DetailView
from .models import *
from django.contrib.auth import login, authenticate
from .forms import *
from django.contrib import messages

# Create your views here.

class MovieList(ListView):
    model = Movie
    paginate_by = 5

class HomeView(ListView):
    model = Movie
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['top_rated'] = Movie.objects.all().order_by('-imdbrating')
        context['year_of_release'] = Movie.objects.all().order_by('-year_of_release')
        context['box_office'] = Movie.objects.all().order_by('-box_office')
        return context

class MovieSearch(ListView):
    model = Movie
    paginate_by = 5

    def get_queryset(self):
        query = self.request.GET.get('query')
        if query:
            object_list = self.model.objects.filter(title__icontains=query)
        else:
            object_list = self.model.objects.none()
        return object_list

def login(request):
    return render(request, 'movie_app/login.html')

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            if User.objects.filter(email=form.cleaned_data['email']).exists():
                messages.error(request,'Email already exists')
            else:
                form.save()
                username = form.cleaned_data.get('username')
                messages.success(request, f'Your account has been created! You are now able to log in')
                return redirect('login')

    else:
        form = UserRegisterForm()
    return render(request, 'movie_app/register.html', {'form': form})

# class MovieDetail(DetailView):
#     model = Movie
    
#     def get_object(self):
#         object = super(MovieDetail, self).get_object()
#         return object

#     def get_context_data(self, **kwargs):
#         context = super(MovieDetail, self).get_context_data(**kwargs)
#         context['related_movie'] = Movie.objects.filter(
#             genre1=self.get_object().genre1)
#         context['genre'] = self.get_object().genre1                             
#         return context

def movie_detail(request, slug):
    template_name = 'movie_app/movie_detail.html'
    movie = get_object_or_404(Movie, slug=slug)
    comments = movie.comments.filter(active=True)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.movie = movie
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    a = Movie.objects.filter(genre1=movie.genre1)
    b = movie.genre1
    return render(request, template_name, {'object': movie,
                                           'related_movie': a,
                                           'genre' : b,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form})

class MovieGenre(ListView):
    model = Movie
    paginate_by = 5

    def get_queryset(self):
        lst=[]
        self.genre = self.kwargs['genre']
        qs1 = Movie.objects.filter(genre1=self.genre)
        qs2 = Movie.objects.filter(genre2=self.genre)
        qs3 = Movie.objects.filter(genre3=self.genre)
        return  qs1.union(qs2,qs3)

    def get_context_data(self, **kwargs):
        context = super(MovieGenre, self).get_context_data(**kwargs)
        context['movie_genre'] = self.genre
        return context
## MACHINE LEARNING PART
class RecommendListView(ListView):
    model = Movie,MyRecommender
    template_name = 'movie_app/recommendations.html'
    context_object_name = 'movies'
    # paginate_by = 6
    def get_queryset(self):
        
        self.title = self.kwargs['title']
        self.username = self.kwargs['username']
        # print(self.title)
        # print(self.username)
        recommend_list = []
        temp_list = recommend.get_recommendations(self.title)
        recommend_list.extend(temp_list)
        #print(recommend_list)
        r = MyRecommender(user_name=self.username, movie_name=recommend_list, liked_movie=self.title)
        r.save()
        return Movie.objects.filter(title__in=recommend_list)


class MyRecommendView(ListView):
    model = MyRecommender
    template_name = 'movie_app/myrecommmender_list.html'
    context_object_name = 'movies'
    #paginate_by = 5

    def get_queryset(self):
        lst=[]
        self.username = self.kwargs['username']
        qs1 = MyRecommender.objects.filter(user_name=self.username)
        for p in qs1:
            for x in p.movie_name:
                lst.append(x)
        print(lst)
        return Movie.objects.filter(title__in=lst)

class MyLikedView(ListView):
    model = MyRecommender
    template_name = 'movie_app/myliked_list.html'
    context_object_name = 'movies'
    #paginate_by = 5

    def get_queryset(self):
        lst=[]
        self.username = self.kwargs['username']
        qs1 = MyRecommender.objects.filter(user_name=self.username)
        for p in qs1:
            lst.append(p.liked_movie)
        print(lst)
        return Movie.objects.filter(title__in=lst)

def contact(request):
    return render(request, 'contact.html')

def about_us(request):
    return render(request, 'about_us.html')

def AddMovie_admin(request):
    if request.method == 'POST':
        form = MovieForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return redirect('add_movie_submission')

    else:
        form = MovieForm()
    return render(request, 'add_admin.html', {'form' : form})

def add_movie_submission(request):
    return render(request, 'add_movie_submission.html')

movie_app/templates/movie_app/login.html
{% load crispy_forms_tags %}
{% load socialaccount %}

{% load static %}

<html lang="en">

<head>
  <title>Login</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!--===============================================================================================-->
  <!-- <link rel="icon" type="image/png" href="images/icons/favicon.ico"/> -->
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
  <!--===============================================================================================-->
  <link rel="shortcut icon" href="{% static 'img/logo122.ico' %}">
  <!-- Link Swiper's CSS -->
  <link rel="stylesheet" href="{% static 'css/swiper.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Lemon&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Lemonada:wght@500&display=swap" rel="stylesheet">
  <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
  <script src="{% static 'js/script.js' %}"></script>
</head>

<body>
  <div class="wrapper">
    <header class="header">
			<figure class="logo"><a style="text-decoration: none;"><img src="{% static 'img/logo122.jpeg' %}" alt="Logo" style=""><p style="color: white; position: relative; left:13px;bottom: 5px;">What2Watch</p></a></figure>
      <!-- 41*224 -->
      <nav class="menu">

      </nav>
      {% if messages %}
        {% for message in messages %}
      <!-- portfolio costruction and analysys python -->
          <div class="alert alert-{{ message.tags }}">
            {{message}}
          </div>
          {% endfor %}
      {% endif %}
      <div class="toggle"><img src="{% static 'img/menu.svg' %}"></div>

      <div class="limiter">
        <div class="container-login100" style="background-image: url('images/bg-01.jpg');">
          <div class="wrap-login100 p-l-55 p-r-55 p-t-30 p-b-10">
            <form id="myForm1" method="POST" class="login100-form validate-form">
              <span class="login100-form-title p-b-30">
                Login
              </span>
              {% csrf_token %}
              {{form|crispy}}


              <div class="text-right p-t-8 p-b-31">

              </div>
              <button class="login100-form-btn">
                Login
              </button>
              <div class="container-login100-form-btn">
                <div class="wrap-login100-form-btn">
                  <div class="login100-form-bgbtn"></div>
                  <button class="login100-form-btn">
                    Login
                  </button>
                </div>
              </div>

              <div class="txt1 text-center p-t-30 p-b-20">
                <span>
                  Or Login Using
                </span>
              </div>

              <div class="flex-c-m">
                <a href="{% provider_login_url 'google' method='js_sdk'%}" class="login100-social-item bg3">
                  <i class="fa fa-google"></i>
                </a>
              </div>

              <div class="flex-col-c p-t-20">

                <a href="register/" class="txt2">
                  <b>NEW HERE? REGISTER !</b>
                </a>
              </div>
            </form>
          </div>
        </div>
      </div>


      <div id="dropDownSelect1"></div>


      <footer class="footer">
        <div class="copyright">
          <p>Copyright &copy 2020 What2Watch</p>
        </div>
        <div class="footermenu">
          <ul>
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="">Contact</a></li>
            <li><a href="">Terms and conditions</a></li>
          </ul>
        </div>
        <div class="tags">
          <ul>
            <li>Discover Movies</li>
            <li>Movie Recommendations</li>
            <li>Search Movies</li>
            <li>Your Favourites</li>
        </div>

        <!--===============================================================================================-->
        <script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
        <!--===============================================================================================-->
        <script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
        <!--===============================================================================================-->
        <script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
        <!--===============================================================================================-->
        <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
        <!--===============================================================================================-->
        <script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
        <script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
        <!--===============================================================================================-->
        <script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
        <!--===============================================================================================-->
        <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

movie_app/templates/movie_app/logout.html
{% load static %}

<html lang="en">

<head>
  <title>Login</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!--===============================================================================================-->
  <!-- <link rel="icon" type="image/png" href="images/icons/favicon.ico"/> -->
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
  <!--===============================================================================================-->
  <link rel="shortcut icon" href="{% static 'img/logo122.ico' %}">
  <!-- Link Swiper's CSS -->
  <link rel="stylesheet" href="{% static 'css/swiper.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Lemon&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Lemonada:wght@500&display=swap" rel="stylesheet">
  <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
  <script src="{% static 'js/script.js' %}"></script>
</head>

<body>
  <div class="wrapper">
    <header class="header">
			<figure class="logo"><a style="text-decoration: none;"><img src="{% static 'img/logo122.jpeg' %}" alt="Logo" style=""><p style="color: white; position: relative; left:13px;bottom: 5px;">What2Watch</p></a></figure>
      <!-- 41*224 -->
      <nav class="menu">
        <ul>
          <li><a href="/">Login</a>
          <li><a href="/register">Register</a>
        </ul>
      </nav>
      
      <div class="toggle"><img src="{% static 'img/menu.svg' %}"></div>

      <div class="limiter">
        <div class="container-login100" style="background-image: url('images/bg-01.jpg');">
          <div class="wrap-login100 p-l-55 p-r-55 p-t-30 p-b-10">
            <h2>You have been logged out</h2>
            <div class="border-top pt-3">
              <small class="text-muted">
                <center><a href="/" class=" txt2">Login Again</a></center>
              </small>
            </div>
          </div>
        </div>
      </div>


      <div id="dropDownSelect1"></div>

      <footer class="footer">
        <div class="copyright">
          <p>Copyright &copy 2020 What2Watch</p>
        </div>
        <div class="footermenu">
          <ul>
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="">Contact</a></li>
            <li><a href="">Terms and conditions</a></li>
          </ul>
        </div>
        <div class="tags">
          <ul>
            <li>Discover Movies</li>
            <li>Movie Recommendations</li>
            <li>Search Movies</li>
            <li>Your Favourites</li>
          </ul>
        </div>

        <!--===============================================================================================-->
        <script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
        <!--===============================================================================================-->
        <script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
        <!--===============================================================================================-->
        <script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
        <!--===============================================================================================-->
        <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
        <!--===============================================================================================-->
        <script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
        <script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
        <!--===============================================================================================-->
        <script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
        <!--===============================================================================================-->
        <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

movie_app/templates/movie_app/movie_detail.html
{% extends 'index.html' %}
{% block body %}
<style>
	.button {
	  background-color: #f4511e;
	  border: none;
	  color: white;
	  padding: 16px 32px;
	  text-align: center;
	  font-size: 16px;
	  margin: 4px 2px;
	  opacity: 1;
	  transition: 0.3s;
	  display: inline-block;
	  text-decoration: none;
	  cursor: pointer;
	}
	
	.button:hover {opacity: 0.6}
	</style>
<main class="content">
	<div class="single">

		<section class="trailer">
			<h3>Movies</h3>
		</section>

		<section class="movie">
			<img src="{{object.image.url}}">
			<ul>
				<li>{{object}}</li>
				<li>{{object.description}}</li>
				<li><a style="color:#f4511e" href="{% url 'movie:movie_genre' object.genre1 %}">{{object.genre1.title}}</a>
					{% if object.genre2 %}
					| <a style="color:#f4511e" href="{% url 'movie:movie_genre' object.genre2 %}">{{object.genre2.title}}</a>
					{% endif %}
					{% if object.genre3 %}
					| <a style="color:#f4511e" href="{% url 'movie:movie_genre' object.genre3 %}">{{object.genre3.title}}</a>
					{% endif %}
				<li><a style="color:#f4511e">Cast: {{object.cast}}</a></li>
				<li>Release Date: {{object.year_of_release}}</li>
				<li>Box Office Collection: ${{object.box_office}}M</li>
				<li>IMDB Rating: {{object.imdbrating}}</li>
			</ul>
		</section>
		<div style="margin-top: 20px;">
			<a href="{% url 'movie:movie_recommend' user.username object.title %}"><button style="margin-top: 35px;" class="button">I Liked this, Recommend me more!</button></a>
		</div>
			<br>
			<br>

		<section class="related">
			<h3>Movies in the {{genre.title}} Genre</h3>
			{% for movie in related_movie %}
			<div class="relatemovie">
				<a href="{% url 'movie:movie_detail' movie.slug %}"><img src="{{movie.image.url}}"></a>
				<a href="{% url 'movie:movie_detail' movie.slug %}"><span class="relatedname">{{movie.title}}</span></a>
			</div>
			{% endfor %}
		</section>

		<section class="related">
			<h3 style="color: cyan;">All Comments</h3>
			<div  class="comments" style="padding: 10px;">
		{% for comment in comments %}
		
        
          <p class="font-weight-bold" style="color: orange;">
            {{ comment.name }}
            <span class=" text-muted font-weight-normal">
              {{ comment.created_on }}
            </span>
		  </p>
			<p class="dialogbox">
				<span class=" tip tip-up"></span>
				  <span  class="message">{{ comment.body}}</span>
			
				<!-- <p style="color: greenyellow;">{{ comment.body}}</p> -->
			</p>
		
        {% endfor %}
			</div>
		<div class="card-body">
			{% if new_comment %}
			<div class="alert alert-success" role="alert">
			  <p style="color: greenyellow;"> Your comment is awaiting moderation</p>
			</div>
			{% else %}
			<h3 style="color: cyan;">Leave a comment !</h3>
			<form id="myForm" method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				{{ comment_form.as_p }}
				<input type="submit" name="submit" value="ADD COMMENT">
			</form>
			{% endif %}
		  </div>
		</section>

	</div>
</main>

{% endblock body %}

movie_app/templates/movie_app/movie_list.html
{% extends 'index.html' %}
{% block body %}

<main class="content">
	<section class="centered">
		{% if movie_genre %}
			<h3>{{movie_genre | title}} Movies</h3>
		{% endif %}
        
		 <div class="movies">
			 {% for movie in object_list %}
			 <div class="mov">
				<a href="{% url 'movie:movie_detail' movie.slug %}">
					<img src="{{movie.image.url}}">
					<h2 class="movietitle">{{movie.title}}
						
					</h2>
				</a>
			</div>
			{% empty %}
			<h3>Opps!! We couldn't find the movie you were looking for!</h3>
			{% endfor %}
		</div>
		{% if is_paginated %}
			<nav class="pagination">
				<ul>
					{% if page_obj.has_previous %}
						<li><a href="?page= {{ page_obj.previos_page_number }}">Prev</a></li>
					{% else %}
						<li class="disabled"></li>
					{% endif %}
					{% for pages in page_obj.paginator.page_range %}
						{% if page_obj.number == pages %}
							<li><a href="#">{{pages}}</a></li>
						{% else %}
							<li><a href="?page={{pages}}">{{pages}}</a></li>
						{% endif %}
					{% endfor %}
					{% if page_obj.has_next %}
						<li><a href="?page= {{ page_obj.next_page_number }}">Next</a></li>
					{% else %}
						<li class="disabled"></li>
					{% endif %}
				</ul>
			</nav>
		{% endif %}
	</section>

</main>



{% endblock body %}

movie_app/templates/movie_app/myliked_list.html
{% extends 'index.html' %}
{% block body %}
<main class="content">
	<div class="single">
		<section class="related">
			<h3>My Liked Movies</h3>
			{% for movie in movies %}
			<div class="relatemovie">
				<a href="{% url 'movie:movie_detail' movie.slug %}"><img src="{{movie.image.url}}"></a>
				<a href="{% url 'movie:movie_detail' movie.slug %}"><span class="relatedname">{{movie.title}}</span></a>
			</div>
			{% endfor %}
		</section>

	</div>
</main>
{% endblock body %}

movie_app/templates/movie_app/myrecommender_list.html
{% extends 'index.html' %}
{% block body %}
<main class="content">
	<div class="single">
		<section class="related">
			<h3>Recommended movies</h3>
			{% for movie in movies %}
			<div class="relatemovie">
				<a href="{% url 'movie:movie_detail' movie.slug %}"><img src="{{movie.image.url}}"></a>
				<a href="{% url 'movie:movie_detail' movie.slug %}"><span class="relatedname">{{movie.title}}</span></a>
			</div>
			{% endfor %}
		</section>

	</div>
</main>
{% endblock body %}

movie_app/templates/movie_app/recommendations.html
{% extends 'index.html' %}
{% block body %}
<main class="content">
	<div class="single">
		<section class="related">
			<h3>Recommended movies</h3>

			{% for movie in movies %}
			<div class="relatemovie">
				<a href="{% url 'movie:movie_detail' movie.slug %}"><img src="{{movie.image.url}}"></a>
				<a href="{% url 'movie:movie_detail' movie.slug %}"><span class="relatedname">{{movie.title}}</span></a>
			</div>
			{% empty %}
			<h3>Sorry, no recommendations found 🙁</h3>
			
			<a href="javascript:history.back()" style="color:orange; position: relative;left:10px;">Go Back</a>

			{% endfor %}
		</section>

		

	</div>
</main>
{% endblock body %}