movie_app/urls.py
from django.urls import path, include
from .views import *

app_name = 'movie'

urlpatterns = [
    path('', MovieList.as_view(), name = 'movie_list'),
    path('search/', MovieSearch.as_view(), name = 'movie_search'),
    path('genre/<str:genre>', MovieGenre.as_view(), name ='movie_genre'),
    path("<slug:slug>/", movie_detail, name="movie_detail"),
    path('recommend/<str:username>/<str:title>', RecommendListView.as_view(), name = 'movie_recommend'),
    path('my_recommendations/<str:username>',MyRecommendView.as_view(),name='my_recommendations'),
    path('my_liked/<str:username>',MyLikedView.as_view(),name='my_liked'),
]

movie_recommender/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from movie_app.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', HomeView.as_view(), name = 'home'),
    path('movie/', include('movie_app.urls', namespace='movie')),
    path('register/', register, name = 'register'),
    path('accounts/', include('allauth.urls')),
    path('contact/', contact, name = 'contact'),
    path('add_admin/', AddMovie_admin, name='add_admin'),
    path('add_movie_submission/', add_movie_submission, name='add_movie_submission'),
    path('about_us/', about_us, name = 'about_us'),
    path('', auth_views.LoginView.as_view(template_name = 'movie_app/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'movie_app/logout.html'), name = 'logout'),
]
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about_us.html
{% extends 'index.html' %}
{% block body %}

		<main class="content">
			<section class="centered">
				<h3>About Us</h3>
				<div class="textcontent">
					<p>
					 What2Watch is a web application which provides an interface consisting of movies, classified into different genres. We rank the movies based on imdb rating, box office collection, and year of release to help you find the best movies till date.
					</p>
					<p>
						We help you find your favourites. Our recommendation algorithm recommends you the best movies for you based on your likings and your taste of movies. There are many apps who recommend movies based on only the rating of other people and their popularity. But our top priority is your choices of movies.
					</p>
					<p>
						Every person has a different personality and so does his/her choices differ. Our goal is to understand their likings and recommend the best for them.
					</p>

				</div>

		</section>

	</main>

	{% endblock body %}

templates/add_admin.html
{% extends 'index.html' %}
{% load static %}
{% block body %}

<main class="content">
	<section class="centered">
		<h3>Add Movie</h3>
		<div class="contact">
			<form id="myForm" action="/add_admin/" method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				{{ form.as_p }}
				<br>
				<p style="color:white">• We support only IMDB standard image sizes.</p>
				<p style="color:white">• Please select a cover image of dimensions 182 x 268 px</p>
				<input type="submit" name="submit" value="ADD MOVIE">
			</form>
		</div>
	</section>

</main>

{% endblock body %}

templates/add_movie_submission.html
{% extends 'index.html' %}
{% load static %}
{% block body %}
<main class="content">
  <section class="centered">
      <span class="success">Movie added succesfully</span>
</section>
{% endblock body %}

templates/contact.html
{% extends 'index.html' %}
{% load static %}
{% block body %}

		<main class="content">
			<section class="centered">
				<h3>Have any queries? Write to us:</h3>
				<div class="contact">
					<form id="myForm" action="mailto:davenishant2k@gmail.com" method="POST" enctype="text/plain">
						<label for="name">Name:</label>
						<input type="text" name="name" id="name">

						<label for="email">Email:</label>
						<input type="email" name="email" id="email">

						<label for="message">Message:</label>
						<textarea id="message" name="message"></textarea>

						<input type="submit" name="submit" value="SEND">
					</form>

			
				</div>
		</section>

	</main>

	{% endblock body %}

templates/home.html
{% extends 'index.html' %}
{% load static %}
{% block body %}

<!--<section class="panel">
<h2>Hey</h2>
</section>-->
<section class="panel">
    <h2>Top Rated Movies</h2>
    <div class="topslider">
      <div class="swiper-container">
        <div class="swiper-wrapper">
          {% for movie in top_rated %}
          <div class="swiper-slide"><a href="{% url 'movie:movie_detail' movie.slug %}"><img src="{{movie.image.url}}">
              <h3 class="hometitle">{{movie.title}} <br>IMDB Rating: {{movie.imdbrating}}/10 </h3>
            </a></div>
          {% endfor %}
          <div class="swiper-slide"><a href="{% url 'movie:movie_list' %}"><img src="{% static 'img/others.png' %}"></a></div>
        </div>
        <div class="nextdirection top-next"><img src="{% static 'img/right-arrow.svg' %}"> </div>
        <div class="leftdirection top-prev"><img src="{% static 'img/left-arrow.svg' %}"> </div>
        <!-- Add Pagination -->
      </div>
    </div>
  </section>

  <section class="panel">
    <h2>Movies by Release Date</h2>
    <div class="topslider">
      <div class="swiper-container">
        <div class="swiper-wrapper">
          {% for movie in year_of_release %}
          <div class="swiper-slide"><a href="{% url 'movie:movie_detail' movie.slug %}"><img src="{{movie.image.url}}">
              <h3 class="hometitle">{{movie.title}} <br>{{movie.year_of_release}} </h3>
            </a></div>
          {% endfor %}
          <div class="swiper-slide"><a href="{% url 'movie:movie_list' %}"><img src="{% static 'img/others.png' %}"></a></div>
        </div>
        <div class="nextdirection top-next"><img src="{% static 'img/right-arrow.svg' %}"> </div>
        <div class="leftdirection top-prev"><img src="{% static 'img/left-arrow.svg' %}"> </div>
        <!-- Add Pagination -->
      </div>
    </div>
  </section>

  <section class="panel">
    <h2>Movies by Box office collections</h2>
    <div class="topslider">
      <div class="swiper-container">
        <div class="swiper-wrapper">
          {% for movie in box_office %}
          <div class="swiper-slide"><a href="{% url 'movie:movie_detail' movie.slug %}"><img src="{{movie.image.url}}">
              <h3 class="hometitle">{{movie.title}} <br>Box Office: ${{movie.box_office}}M  </h3>
            </a></div>
          {% endfor %}
          <div class="swiper-slide"><a href="{% url 'movie:movie_list' %}"><img src="{% static 'img/others.png' %}"></a></div>
        </div>
        <div class="nextdirection top-next"><img src="{% static 'img/right-arrow.svg' %}"> </div>
        <div class="leftdirection top-prev"><img src="{% static 'img/left-arrow.svg' %}"> </div>
        <!-- Add Pagination -->
      </div>
    </div>
  </section>

{% endblock body %}

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>What2Watch</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
	<link rel="shortcut icon" href="{% static 'img/logo122.ico' %}">
	<!-- Link Swiper's CSS -->
	<!-- <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"> -->
	<link rel="stylesheet" href="{% static 'css/swiper.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">
	<link href="https://fonts.googleapis.com/css2?family=Lemon&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Lemonada:wght@500&display=swap" rel="stylesheet">
	<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
	<script src="{% static 'js/script.js' %}"></script>
	<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	<!-- Demo styles -->
	<style>
		article,
		aside,
		figure,
		footer,
		header,
		hgroup,
		menu,
		nav,
		section {
			display: block;
		}
	</style>
</head>

<body>
	
	<div class="wrapper">
		<header class="header">
			<figure class="logo"><a style="text-decoration: none;" href="{% url 'home' %}"><img src="{% static 'img/logo122.jpeg' %}" alt="Logo" style=""><p style="color: white; position: relative; left:13px;bottom: 5px;">What2Watch</p></a></figure>
			<!-- 41*224 -->
			<nav class="menu">
				<ul>
					<li><a href="{% url 'home' %}">Home</a></li>
					<li><a>Genres</a>
                        <ul>
							<li><a href="{% url 'movie:movie_genre' 'action' %}">Action</a></li>
							<li><a href="{% url 'movie:movie_genre' 'adventure' %}">Adventure</a></li>
							<li><a href="{% url 'movie:movie_genre' 'fantasy' %}">Fantasy</a></li>
							<li><a href="{% url 'movie:movie_genre' 'romance' %}">Romance</a></li>
							<li><a href="{% url 'movie:movie_genre' 'comedy' %}">Comedy</a></li>
							<li><a href="{% url 'movie:movie_genre' 'science_fiction' %}">Sci Fi</a></li>							
						</ul>
					</li>
					<li><a href="{% url 'movie:my_recommendations' user.username %}">My Recommendations</a>	
					</li>
					<li><a href="{% url 'movie:my_liked' user.username %}">Liked Movies</a>
						
					</li>
					<li class="mobsearch">
						<form class="mobform" method="GET">
							<input type="text" name="query" value="{{ request.GET.q }}" class="mobsearchfield" placeholder="Search...">
							<input type="submit" value="" class="mobsearchsubmit">
						</form>
					</li>
					<form class="search" method="GET" action="{% url 'movie:movie_search' %}">
						<input type="text" name="query" value="{{ request.GET.q }}" class="searchfield" placeholder="Search...">
						<input type="submit" value="" class="searchsubmit">
					</form>
					
					{% if user.is_superuser %}
					<li class="navbar-nav" style="position: absolute; right: 190px;"><a>Welcome, {{user.username}}</a></li>
					<li style="position: absolute; right:100px; color:white;"><a href="{% url 'add_admin' %}">Add Movie</a></li>
					{% else %}
					<li class="navbar-nav" style="position: absolute; right: 100px;"><a>Welcome, {{user.username}}</a></li>
					{% endif %}
					<li class="navbar-nav" style="position: absolute; right: 20px;"><a href="{% url 'logout' %}">Logout</a></li>
				
				</ul>
				
			</nav>
		</header>
		<!-- Swiper -->
		<div class="homeslider">
			<div class="swiper-container">
				<div class="swiper-wrapper">
					<div class="swiper-slide">
						<img src="{% static 'images/slider/avengers.jpg' %}">
						<div class="caption">
							<div class="captioninside">
								<h3 style="font-family: 'Lemon', cursive;">"No good movie is too long and no bad movie is short enough."</h3>
								<p style="font-family: 'Lemonada', cursive;">-Roger Ebert</p>
							</div>
						</div>
					</div>
					<div class="swiper-slide">
						<img src="{% static 'images/slider/avatar.jpg' %}">
						<div class="caption">
							<div class="captioninside">
								<h3 style="font-family: 'Lemon', cursive;">"Every great film should seem new every time you see it."</h3>
								<p style="font-family: 'Lemonada', cursive;">-Roger Ebert</p>
							</div>
						</div>
					</div>
					<div class="swiper-slide">
						<img src="{% static 'images/slider/pirates_of_caribbean.jpg' %}">
						<div class="caption">
							<div class="captioninside">
								<h3 style="font-family: 'Lemon', cursive;">"Art is the closest we can come to understanding how a stranger really feels."</h3>
								<p style="font-family: 'Lemonada', cursive;">-Roger Ebert</p>
							</div>
						</div>
					</div>
					<div class="swiper-slide">
						<img src="{% static 'images/slider/spiderman.jpg' %}">
						<div class="caption">
							<div class="captioninside">
								<strong></strong>
								<h3 style="font-family: 'Lemon', cursive;">"Most of us do not consciously look at movies."</h3>
								<p style="font-family: 'Lemonada', cursive;">-Roger Ebert</p>
							</div>
						</div>
					</div>
				</div>
				<!-- Add Pagination -->
				<div class="swiper-pagination"></div>
			</div>
		</div>


		{% block body %}
		{% endblock body %}

		<footer class="footer">
			<div class="copyright">
				<p>Copyright &copy 2020 What2Watch</p>
			</div>
			<div class="footermenu">
				<ul>
					<li><a href="{% url 'home' %}">Home</a></li>
					<li><a href="{% url 'about_us' %}">About Us</a></li>
					<li><a href="{% url 'contact' %}">Have Queries?</a></li>

				</ul>
			</div>
			<div class="tags">
				<ul>
					<li>Discover Movies</li>
					<li>Movie Recommendations</li>
					<li>Search Movies</li>
					<li>Your Favourites</li>
				</ul>
			</div>

		</footer>
		<!-- Swiper JS -->
		<script src="{% static 'js/swiper.min.js' %}"></script>
		<!-- Initialize Swiper -->
		<script>
			$(document).ready(function() {
				var swiper = new Swiper('.homeslider > .swiper-container', {
					autoplay: 5000,
					speed: 2000,
					pagination: '.swiper-pagination',
					paginationClickable: true,
					preventClicks: false,
					preventClicksPropagation: false,
					effect: 'fade',
					breakpoints: {
						320: {
							height: 200
						},

						480: {
							height: 300
						},

						768: {
							height: 400
						},
						1024: {
							height: 500
						}
					}
				});

				var recentswiper = new Swiper('.recentslider > .swiper-container', {
					nextButton: '.recent-next',
					prevButton: '.recent-prev',
					slidesPerView: 8,
					paginationClickable: true,
					preventClicks: false,
					preventClicksPropagation: false,
					spaceBetween: 10,
					breakpoints: {
						320: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						480: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						768: {
							slidesPerView: 5,
							spaceBetween: 5
						},
						1024: {
							slidesPerView: 6,
							spaceBetween: 10
						}
					}
				});

				var mostswiper = new Swiper('.mostslider > .swiper-container', {
					nextButton: '.most-next',
					prevButton: '.most-prev',
					slidesPerView: 8,
					paginationClickable: true,
					preventClicks: false,
					preventClicksPropagation: false,
					spaceBetween: 10,
					breakpoints: {
						320: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						480: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						768: {
							slidesPerView: 5,
							spaceBetween: 5
						},
						1024: {
							slidesPerView: 6,
							spaceBetween: 10
						}
					}
				});

				var topswiper = new Swiper('.topslider > .swiper-container', {
					nextButton: '.top-next',
					prevButton: '.top-prev',
					slidesPerView: 8,
					paginationClickable: true,
					preventClicks: false,
					preventClicksPropagation: false,
					spaceBetween: 10,
					breakpoints: {
						320: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						480: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						768: {
							slidesPerView: 5,
							spaceBetween: 5
						},
						1024: {
							slidesPerView: 6,
							spaceBetween: 10
						}
					}
				});

			});
		</script>
	</div>
</body>

</html>